Speex *should* now work on big-endian architectures.
git-svn-id: http://svn.xiph.org/trunk/speex@3384 0101bb08-14d6-0310-b084-bc0e0c8e3800

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -32,9 +32,16 @@ dnl AC_DISABLE_STATIC
 AM_PROG_LIBTOOL
 
 AC_C_BIGENDIAN
-AC_CHECK_HEADERS(sys/soundcard.h ogg/ogg.h)
+AC_CHECK_HEADERS(sys/soundcard.h)
+src=src
+AC_CHECK_HEADERS(aogg/ogg.h, [], [src=])
 AC_CHECK_LIB(m, sin)
-AC_CHECK_LIB(ogg, ogg_stream_init, [LIB_OGG='-logg'; AC_SUBST(LIB_OGG)] , [ echo; echo "error: libogg is now required by speex"; echo "Get it from: http://www.ogg.org/ogg/index.html"; exit 1 ])
+
+AC_CHECK_LIB(ogg, ogg_stream_init, [LIB_OGG='-logg'; AC_SUBST(LIB_OGG)] , [ src=])
+AC_SUBST(src)
+
+dnl AC_CHECK_LIB(ogg, ogg_stream_init, [LIB_OGG='-logg'; AC_SUBST(LIB_OGG)] , [ echo; echo "error: libogg is now required by speex"; echo "Get it from: http://www.ogg.org/ogg/index.html"; exit 1 ])
+
 AC_FUNC_ALLOCA
 dnl AC_DEFINE(VERSION, "$VERSION")
 AC_DEFINE_UNQUOTED(VERSION, "${VERSION}")
@@ -43,3 +50,9 @@ dnl Output the makefiles and version.h.
 
 AC_OUTPUT([Makefile libspeex/Makefile src/Makefile Speex.spec ])
 
+if test "x$src" = "x"; then 
+echo "You don't seem to have libogg installed. Only the Speex library (libspeex) will be built (no encoder/decoder executable)"
+echo "You can get libogg from http://www.ogg.org/ogg/index.html"
+fi
+
+echo "Type \"make; make install\" to compile and install Speex";
